# Generated by Django 5.1.1 on 2024-09-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='avtor',
        ),
        migrations.AddField(
            model_name='profile',
            name='url',
            field=models.ManyToManyField(to='shop.url'),
        ),
    ]
