# Generated by Django 5.1.1 on 2024-09-25 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='url',
        ),
        migrations.DeleteModel(
            name='Url',
        ),
    ]
