# Generated by Django 5.1.1 on 2024-09-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_profile_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='text',
            field=models.TextField(default='Я так обожаю сладкий раф с сахаром и карамельным сиропом :)'),
        ),
    ]
