# Generated by Django 5.1.1 on 2024-09-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='urls',
            field=models.JSONField(null=True),
        ),
    ]
