# Generated by Django 5.1.1 on 2024-09-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_profile_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='url',
            field=models.CharField(max_length=4096, null=True),
        ),
    ]
