# Generated by Django 5.1.1 on 2024-09-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_url_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
